[window]
opacity = 0.5

[font]
size = 12

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[colors]
cursor = { text = "#11111B", cursor = "#CBA6F7" }

[colors.primary]
foreground = "#CDD6F4"
background = "#11111B"

[colors.search]
matches = { foreground = "#89B4FA", background = "#11111B"}
focused_match = { foreground = "#89B4FA", background = "#CBA6F7"}

[colors.normal]
black = "#11111B"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#CBA6F7"
cyan = "#B4BEFE"
white = "#CDD6F4"

[colors.bright]
black = "#11111B"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#CBA6F7"
cyan = "#B4BEFE"
white = "#CDD6F4"